data_root: "D:/cryst/ECE4500J/Autonomous-Wheel-Loader-Perception/data/sequence1" # TODO
data_type: "fr1"
near: 0.01
far: 2.0
vol_bounds: [-2.5, 3., -3.2, 3., -0.2, 3.]
voxel_size: 0.01
n_pyramids: 4
n_iters: [10, 3, 3, 3]
dampings: [1.0e-4, 1.0e-4, 1.0e-2, 1.0e-2]
n_steps: 256